[package]
name = "time"
version = "1.0.0"
description = "Nano, micro, millis, seconds timestamp to string date or DateType"
repository = "https://github.com/ArielRobotti/time"
keywords = [
  "Time",
  "Timestamp",
  "Seconds",
  "Milliseconds",
  "Microseconds",
  "Nanoseconds",
  "Date",
  "Datestring"
]
license = "MIT"