[package]
name = "time"
version = "1.0.5"
description = "Nano, micro, millis, seconds timestamp to string date or DateType"
repository = "https://github.com/ArielRobotti/time"
keywords = [
  "Date",
  "Time",
  "Timestamp",
  "Seconds",
  "Milliseconds",
  "Microseconds",
  "Nanoseconds",
  "Datestring",
  "StringDate"
]
license = "MIT"

[dependencies]
base = "0.10.4"